# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglik_cpp_R6 <- function(V, betahat, shat2, prior_weight, nancestry, diag_index) {
    .Call(`_INFUSE_loglik_cpp_R6`, V, betahat, shat2, prior_weight, nancestry, diag_index)
}

mvlmm_reg <- function(betahat, shat2, V_mat) {
    .Call(`_INFUSE_mvlmm_reg`, betahat, shat2, V_mat)
}

test_ELBO <- function(alpha, mu1, mu2, XtX, XtX_diag, Xty, yty, N_vec, sigma2, KL) {
    .Call(`_INFUSE_test_ELBO`, alpha, mu1, mu2, XtX, XtX_diag, Xty, yty, N_vec, sigma2, KL)
}

test_run_loglik_cpp <- function(V, betahat, shat2, prior_weight, nancestry, diag_index, config_list) {
    .Call(`_INFUSE_test_run_loglik_cpp`, V, betahat, shat2, prior_weight, nancestry, diag_index, config_list)
}

test_run_mvlmm_reg <- function(betahat, shat2, V_mat) {
    .Call(`_INFUSE_test_run_mvlmm_reg`, betahat, shat2, V_mat)
}

estimate_prior_annot <- function(annot_file_subset, alpha) {
    .Call(`_INFUSE_estimate_prior_annot`, annot_file_subset, alpha)
}

llk_prior_causal_cpp <- function(w, annotation, alpha) {
    .Call(`_INFUSE_llk_prior_causal_cpp`, w, annotation, alpha)
}

optimize_llk <- function(annotation, alpha, initial_w) {
    .Call(`_INFUSE_optimize_llk`, annotation, alpha, initial_w)
}

rcpp_hello_world <- function() {
    .Call(`_INFUSE_rcpp_hello_world`)
}

